network:
  ethernets:
    enp0s3:
      addresses:
      - 192.168.192.168/22
      gateway4: 192.168.192.254
      nameservers:
        addresses:
        - 172.16.132.245
        - 172.16.133.246
        - 172.16.134.247
        search:
        - local.wildfielded.site
        - wildfielded.site
        - ssszone.ru
  version: 2
