network:
  version: 2
  renderer: networkd
  ethernets:

    ##### Static IP
    enp0s3:
      addresses:
      - 192.168.192.168/22
      - 10.10.10.10/27
      gateway4: 192.168.192.254
      routes:
      - to: 10.20.30.0/24
        via: 10.10.10.30
        on-link: true
      nameservers:
        addresses:
        - 172.16.132.245
        - 172.16.133.246
        - 172.16.134.247
        search:
        - local.wildfielded.site
        - wildfielded.site
        - ssszone.ru

    ##### Simple DHCP
    enp0s4:
      dhcp4: true

    ##### DHCP with MAC-address spoofing
    ens1f5:
      match:
        ##### Real MAC
        macaddress: 80:aa:bc:de:f8:74
      ##### Spoofed MAC
      macaddress: 00:07:0e:de:ca:f4
      dhcp4: true
